# -*- coding: utf-8 -*-
"""Salinan infant_cry_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxVlQ11dmpZoOwd2yl85-C7ij1BdjJiW

# Klasifikasi Jenis Tangisan Bayi (Infant Cry Classification)

**Dataset:** Donate-a-Cry Corpus (`infant-cry-audio-corpus`)
**Kelas:** `belly_pain` (16), `burping` (8), `discomfort` (27), `hungry` (382), `tired` (24) — total 457 file, **sangat imbalanced**

**Alur pengerjaan:**
1. Import
2. Data Cleaning
3. Data Splitting
4. Data Preprocessing
5. Ekstraksi Fitur
6. Training Model (Tradisional & Modern)
7. Evaluasi Model
8. Perbandingan Model Tradisional vs Modern

**Catatan penting:**
- Segmentasi audio menjadi window **2 detik** dilakukan untuk augmentasi data sekaligus menyeragamkan panjang audio.
- Untuk ML tradisional (SVM, Random Forest): fitur domain waktu (RMS Energy, ZCR), domain frekuensi (Spectral Centroid, Spectral Bandwidth), Pitch, dan MFCC — diringkas dengan *feature engineering* (mean, std, min, max).
- Untuk ML modern (CNN, CNN-LSTM): representasi **mel-spectrogram** sebagai input.
- Jumlah data akan dicatat pada setiap tahap: setelah segmentasi, dan setelah augmentasi.

---
## 1. Import

Mount Google Drive, install & import seluruh library yang dibutuhkan.
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install library yang belum tersedia default di Colab
!pip install librosa soundfile audiomentations scikit-learn tensorflow -q

# Import library
import os
import glob
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import librosa
import librosa.display
import soundfile as sf

from audiomentations import Compose, AddGaussianNoise, TimeStretch, PitchShift, Shift

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                              f1_score, confusion_matrix, classification_report)

import tensorflow as tf
from tensorflow.keras import layers, models, callbacks

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)
tf.random.set_seed(RANDOM_STATE)

SAMPLE_RATE = 22050          # target sampling rate untuk resampling
SEGMENT_DURATION = 2.0       # durasi segmentasi audio (detik)
SEGMENT_LENGTH = int(SAMPLE_RATE * SEGMENT_DURATION)

DATASET_DIR = '/content/drive/MyDrive/Colab Notebooks/Matkul/PPDM/donateacry_corpus'
CLASSES = ['belly_pain', 'burping', 'discomfort', 'hungry', 'tired']

print("Setup selesai.")

"""---
## 2. Pemahaman Domain dan Dataset

**Masalah klasifikasi:** Mengidentifikasi jenis kebutuhan/kondisi bayi berdasarkan karakteristik akustik tangisannya (audio classification, multi-class, single-label).

**Kelas yang diprediksi (5 kelas):**
| Kelas | Deskripsi |
|---|---|
| `belly_pain` | Tangisan akibat sakit perut/kolik |
| `burping` | Tangisan bayi yang perlu bersendawa |
| `discomfort` | Tangisan akibat ketidaknyamanan (popok, suhu, dll.) |
| `hungry` | Tangisan akibat lapar |
| `tired` | Tangisan akibat lelah/mengantuk |

Dataset bersifat **imbalanced** — kelas `hungry` mendominasi (382 dari 457 file, ~83.6%), sedangkan `burping` hanya 8 file. Hal ini akan ditangani lewat **augmentasi data** setelah data splitting (augmentasi hanya pada data train agar tidak bocor ke test set).
"""

# Cek jumlah file mentah per kelas
raw_counts = {}
for cls in CLASSES:
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    raw_counts[cls] = len(files)

df_raw = pd.DataFrame(list(raw_counts.items()), columns=['class', 'jumlah_file'])
df_raw['persentase'] = (df_raw['jumlah_file'] / df_raw['jumlah_file'].sum() * 100).round(2)
print(f"Total file mentah: {df_raw['jumlah_file'].sum()}")
df_raw

"""---
## 3. EDA (Exploratory Data Analysis) Audio

Meliputi: distribusi kelas, distribusi durasi audio, visualisasi waveform, dan visualisasi spectrogram.

### 3.1 Distribusi Kelas
"""

plt.figure(figsize=(8, 5))
sns.barplot(data=df_raw, x='class', y='jumlah_file', hue='class', palette='viridis', legend=False)
plt.title('Distribusi Jumlah File Audio per Kelas (Data Mentah)')
plt.xlabel('Kelas')
plt.ylabel('Jumlah File')
for i, v in enumerate(df_raw['jumlah_file']):
    plt.text(i, v + 5, str(v), ha='center', fontweight='bold')
plt.tight_layout()
plt.show()

"""### 3.2 Distribusi Durasi Audio"""

durations = []
labels_dur = []
for cls in CLASSES:
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    for f in files:
        try:
            d = librosa.get_duration(path=f)
            durations.append(d)
            labels_dur.append(cls)
        except Exception as e:
            print(f"Gagal baca {f}: {e}")

df_dur = pd.DataFrame({'class': labels_dur, 'duration': durations})
print(df_dur['duration'].describe())

# Histogram terpisah per kelas (grid subplot, bukan stacked)
fig, axes = plt.subplots(1, len(CLASSES), figsize=(4 * len(CLASSES), 4), sharey=False)
colors = sns.color_palette('tab10', len(CLASSES))
for i, cls in enumerate(CLASSES):
    sub = df_dur[df_dur['class'] == cls]
    axes[i].hist(sub['duration'], bins=20, color=colors[i], edgecolor='black')
    axes[i].set_title(cls)
    axes[i].set_xlabel('Durasi (detik)')
    if i == 0:
        axes[i].set_ylabel('Jumlah File')
fig.suptitle('Distribusi Durasi Audio per Kelas', y=1.03)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df_dur, x='class', y='duration', hue='class', palette='Set2', legend=False)
plt.title('Boxplot Durasi Audio per Kelas')
plt.tight_layout()
plt.show()

"""### 3.3 Visualisasi Waveform (Contoh per Kelas)"""

fig, axes = plt.subplots(len(CLASSES), 1, figsize=(12, 2.5 * len(CLASSES)))
for i, cls in enumerate(CLASSES):
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    y, sr = librosa.load(files[0], sr=SAMPLE_RATE)
    librosa.display.waveshow(y, sr=sr, ax=axes[i], color=sns.color_palette('viridis', len(CLASSES))[i])
    axes[i].set_title(f'Waveform - {cls} (contoh: {os.path.basename(files[0])})')
    axes[i].set_ylabel('Amplitudo')
plt.tight_layout()
plt.show()

"""### 3.4 Visualisasi Spectrogram (Contoh per Kelas)"""

fig, axes = plt.subplots(len(CLASSES), 1, figsize=(12, 3 * len(CLASSES)))
for i, cls in enumerate(CLASSES):
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    y, sr = librosa.load(files[0], sr=SAMPLE_RATE)
    D = librosa.amplitude_to_db(np.abs(librosa.stft(y)), ref=np.max)
    img = librosa.display.specshow(D, sr=sr, x_axis='time', y_axis='hz', ax=axes[i], cmap='magma')
    axes[i].set_title(f'Spectrogram - {cls}')
    fig.colorbar(img, ax=axes[i], format='%+2.0f dB')
plt.tight_layout()
plt.show()

"""### 3.5 Visualisasi MFCC (Contoh per Kelas)"""

fig, axes = plt.subplots(len(CLASSES), 1, figsize=(12, 3 * len(CLASSES)))
for i, cls in enumerate(CLASSES):
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    y, sr = librosa.load(files[0], sr=SAMPLE_RATE)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    img = librosa.display.specshow(mfcc, sr=sr, x_axis='time', ax=axes[i], cmap='coolwarm')
    axes[i].set_title(f'MFCC (13 koefisien) - {cls}')
    axes[i].set_ylabel('Koefisien MFCC')
    fig.colorbar(img, ax=axes[i])
plt.tight_layout()
plt.show()

"""---
## 4. Data Cleaning

Membuang file yang korup / tidak bisa dibaca / berdurasi 0 detik, lalu membangun manifest (daftar path file + label) sebagai acuan tahap selanjutnya.
"""

records = []
corrupt_files = []

for cls in CLASSES:
    files = glob.glob(os.path.join(DATASET_DIR, cls, '*.wav'))
    for f in files:
        try:
            y, sr = librosa.load(f, sr=None)
            if len(y) == 0 or np.all(y == 0):
                corrupt_files.append(f)
                continue
            records.append({'filepath': f, 'label': cls})
        except Exception as e:
            corrupt_files.append(f)
            print(f"File korup dibuang: {f} ({e})")

df_manifest = pd.DataFrame(records)
print(f"File korup/dibuang: {len(corrupt_files)}")
print(f"Total file valid setelah cleaning: {len(df_manifest)}")
df_manifest['label'].value_counts()

"""---
## 5. Data Splitting

Split dilakukan **sebelum** preprocessing/augmentasi dan berbasis **file asli** (bukan segmen), menggunakan stratified split agar proporsi kelas tetap terjaga di tiap subset. Ini penting supaya segmen dari file yang sama tidak bocor antara train dan test (mencegah *data leakage*).

Rasio: 70% train, 15% validation, 15% test.
"""

train_df, temp_df = train_test_split(
    df_manifest, test_size=0.3, stratify=df_manifest['label'], random_state=RANDOM_STATE
)
val_df, test_df = train_test_split(
    temp_df, test_size=0.5, stratify=temp_df['label'], random_state=RANDOM_STATE
)

train_df = train_df.reset_index(drop=True)
val_df = val_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print(f"Train : {len(train_df)} file")
print(f"Val   : {len(val_df)} file")
print(f"Test  : {len(test_df)} file")
print()
print("Distribusi kelas - Train:")
print(train_df['label'].value_counts())
print()
print("Distribusi kelas - Val:")
print(val_df['label'].value_counts())
print()
print("Distribusi kelas - Test:")
print(test_df['label'].value_counts())

"""---
## 6. Data Preprocessing

Tahapan: **Resampling → Normalisasi → Trimming Silence → Segmentasi (2 detik, khusus infant cry) → Augmentasi (khusus train)**.

Segmentasi 2 detik berfungsi ganda: menyeragamkan panjang audio (dibutuhkan CNN/mel-spectrogram) sekaligus menambah jumlah data (satu file panjang bisa menghasilkan beberapa segmen).
"""

def load_and_preprocess(filepath, sr=SAMPLE_RATE):
    """Resampling + normalisasi + trimming silence."""
    y, _ = librosa.load(filepath, sr=sr)          # resampling ke target SR
    y, _ = librosa.effects.trim(y, top_db=25)       # trimming silence
    if np.max(np.abs(y)) > 0:
        y = y / np.max(np.abs(y))                   # normalisasi amplitudo ke [-1, 1]
    return y

def segment_audio(y, segment_length=SEGMENT_LENGTH, sr=SAMPLE_RATE):
    """Segmentasi audio jadi window tetap (2 detik).
    Audio lebih pendek dari 2 detik di-pad (zero padding).
    Audio lebih panjang dipecah jadi beberapa segmen non-overlap.
    """
    segments = []
    if len(y) <= segment_length:
        padded = np.pad(y, (0, segment_length - len(y)), mode='constant')
        segments.append(padded)
    else:
        n_segments = len(y) // segment_length
        for i in range(n_segments):
            segments.append(y[i*segment_length:(i+1)*segment_length])
        remainder = len(y) - n_segments * segment_length
        if remainder > segment_length * 0.5:  # sisa signifikan -> pad jadi 1 segmen tambahan
            last = y[n_segments*segment_length:]
            last = np.pad(last, (0, segment_length - len(last)), mode='constant')
            segments.append(last)
    return segments

"""### 6.0 Visualisasi Pipeline Preprocessing

Contoh dipilih dari file yang berdurasi cukup panjang (>4 detik) supaya proses segmentasi menghasilkan lebih dari 1 segmen dan terlihat jelas. Baris 1: raw vs trim+normalisasi (durasi tetap sama, cuma silence & amplitudo yang berubah). Baris 2: seluruh segmen 2 detik hasil pemecahan sinyal baris 1.
"""

# Cari contoh file yang durasinya > 4 detik (biar hasil segmentasi > 1 segmen, ada di kelas hungry)
sample_row = None
for _, row in train_df[train_df['label'] == 'hungry'].iterrows():
    dur = librosa.get_duration(path=row['filepath'])
    if dur > 4.0:
        sample_row = row
        break
if sample_row is None:
    sample_row = train_df[train_df['label'] == 'hungry'].iloc[0]

sample_path = sample_row['filepath']
sample_label = sample_row['label']

# Tahap 1: Raw
y_raw, sr_raw = librosa.load(sample_path, sr=SAMPLE_RATE)

# Tahap 2: Trim + Normalisasi
y_clean = load_and_preprocess(sample_path)

# Tahap 3: Segmentasi jadi window 2 detik
sample_segments = segment_audio(y_clean)

print(f"File   : {os.path.basename(sample_path)} (kelas: {sample_label})")
print(f"Durasi raw   : {len(y_raw)/SAMPLE_RATE:.2f}s")
print(f"Durasi clean : {len(y_clean)/SAMPLE_RATE:.2f}s")
print(f"Jumlah segmen hasil split : {len(sample_segments)}")

n_segments = len(sample_segments)
n_cols_row2 = max(n_segments, 2)  # minimal 2 kolom biar grid gak aneh

fig = plt.figure(figsize=(5 * max(2, n_cols_row2), 8))
gs = fig.add_gridspec(2, n_cols_row2)

# --- Baris 1: Raw & Trim+Normalisasi ---
ax1 = fig.add_subplot(gs[0, 0:n_cols_row2//2 if n_cols_row2 > 2 else 1])
librosa.display.waveshow(y_raw, sr=SAMPLE_RATE, ax=ax1, color='tab:blue')
ax1.set_title(f'1. Raw — dur={len(y_raw)/SAMPLE_RATE:.2f}s')
ax1.set_ylabel('Amplitudo')

ax2 = fig.add_subplot(gs[0, n_cols_row2//2 if n_cols_row2 > 2 else 1:n_cols_row2])
librosa.display.waveshow(y_clean, sr=SAMPLE_RATE, ax=ax2, color='tab:orange')
ax2.set_title(f'2. Trim + Normalisasi — dur={len(y_clean)/SAMPLE_RATE:.2f}s')

# --- Baris 2: Semua segmen hasil split (2 detik per segmen) ---
for i, seg in enumerate(sample_segments):
    ax = fig.add_subplot(gs[1, i])
    librosa.display.waveshow(seg, sr=SAMPLE_RATE, ax=ax, color='tab:green')
    ax.set_title(f'3.{i+1} Segmen {i+1} — dur=2.00s')
    ax.set_xlabel('Waktu (s)')
    if i == 0:
        ax.set_ylabel('Amplitudo')

fig.suptitle(f'Pipeline Preprocessing ({sample_label} sample)', fontsize=13)
plt.tight_layout()
plt.show()

def build_segmented_set(df):
    """Load, preprocess, dan segmentasi seluruh file dalam df.
    Return list segmen audio + label masing-masing."""
    X_segments, y_labels, source_files = [], [], []
    for _, row in df.iterrows():
        y = load_and_preprocess(row['filepath'])
        segs = segment_audio(y)
        for s in segs:
            X_segments.append(s)
            y_labels.append(row['label'])
            source_files.append(row['filepath'])
    return X_segments, y_labels, source_files

train_segments, train_labels, train_sources = build_segmented_set(train_df)
val_segments, val_labels, val_sources = build_segmented_set(val_df)
test_segments, test_labels, test_sources = build_segmented_set(test_df)

print("=== Jumlah data SETELAH SEGMENTASI (2 detik) ===")
print(f"Train : {len(train_df)} file  ->  {len(train_segments)} segmen")
print(f"Val   : {len(val_df)} file  ->  {len(val_segments)} segmen")
print(f"Test  : {len(test_df)} file  ->  {len(test_segments)} segmen")
print()
print("Distribusi kelas segmen - Train:")
print(pd.Series(train_labels).value_counts())

"""### 6.1 Augmentasi Data (khusus Train Set)

Augmentasi dilakukan **hanya pada train set** untuk menambah variasi data sekaligus menyeimbangkan kelas minoritas (`burping`, `belly_pain`, `tired`, `discomfort`) mendekati jumlah kelas mayoritas (`hungry`). Teknik: Gaussian noise, time stretch, pitch shift, dan time shift.
"""

augmenter = Compose([
    AddGaussianNoise(min_amplitude=0.001, max_amplitude=0.01, p=0.5),
    TimeStretch(min_rate=0.9, max_rate=1.1, p=0.5),
    PitchShift(min_semitones=-2, max_semitones=2, p=0.5),
    Shift(p=0.3),
])

def augment_segment(y, sr=SAMPLE_RATE, segment_length=SEGMENT_LENGTH):
    aug = augmenter(samples=y.astype(np.float32), sample_rate=sr)
    # jaga-jaga panjang berubah akibat time stretch -> paksa balik ke segment_length
    if len(aug) < segment_length:
        aug = np.pad(aug, (0, segment_length - len(aug)), mode='constant')
    else:
        aug = aug[:segment_length]
    return aug

# Augmentasi untuk menyeimbangkan kelas pada train set
train_labels_arr = np.array(train_labels)
class_counts = pd.Series(train_labels_arr).value_counts()
target_count = class_counts.max()  # jadikan kelas mayoritas sebagai target

print("Jumlah segmen train SEBELUM augmentasi:")
print(class_counts)

aug_segments, aug_labels, aug_sources = [], [], []

for cls in CLASSES:
    idx_cls = [i for i, l in enumerate(train_labels) if l == cls]
    current_count = len(idx_cls)
    n_needed = max(0, target_count - current_count)
    for _ in range(n_needed):
        src_idx = random.choice(idx_cls)
        aug_y = augment_segment(train_segments[src_idx])
        aug_segments.append(aug_y)
        aug_labels.append(cls)
        aug_sources.append(train_sources[src_idx] + '_AUG')

# Gabungkan data asli (segmented) train + hasil augmentasi
train_segments_final = train_segments + aug_segments
train_labels_final = train_labels + aug_labels
train_sources_final = train_sources + aug_sources

print()
print("=== Jumlah data SETELAH AUGMENTASI (train set) ===")
print(f"Sebelum augmentasi : {len(train_segments)} segmen")
print(f"Hasil augmentasi   : {len(aug_segments)} segmen baru")
print(f"Total setelah augmentasi : {len(train_segments_final)} segmen")
print()
print("Distribusi kelas train setelah augmentasi:")
print(pd.Series(train_labels_final).value_counts())

# Ringkasan jumlah data di setiap tahap
summary_stage = pd.DataFrame({
    'Tahap': ['File mentah (setelah cleaning)', 'Segmen (train)', 'Segmen (val)',
              'Segmen (test)', 'Train setelah augmentasi'],
    'Jumlah': [len(df_manifest), len(train_segments), len(val_segments),
               len(test_segments), len(train_segments_final)]
})
summary_stage

"""---
## 7. Ekstraksi Fitur

**Untuk ML Tradisional (SVM, Random Forest):**
- Domain waktu: RMS Energy, Zero Crossing Rate (ZCR)
- Domain frekuensi: Spectral Centroid, Spectral Bandwidth
- Representasi tambahan: Pitch (F0) via `librosa.pyin`
- Representasi utama: MFCC (13 koefisien)

**Untuk ML Modern (CNN, CNN-LSTM):**
- Mel-Spectrogram (2D time-frequency representation)

### 7.1 Fungsi Ekstraksi Fitur (Domain Waktu, Frekuensi, MFCC, Pitch)
"""

N_MFCC = 13

def extract_features_traditional(y, sr=SAMPLE_RATE, n_mfcc=N_MFCC):
    """Ekstrak seluruh fitur frame-level untuk satu segmen audio.
    Return dict berisi array time-series tiap fitur (sebelum feature engineering)."""
    # Domain waktu
    rms = librosa.feature.rms(y=y)[0]
    zcr = librosa.feature.zero_crossing_rate(y=y)[0]

    # Domain frekuensi
    spectral_centroid = librosa.feature.spectral_centroid(y=y, sr=sr)[0]
    spectral_bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)[0]

    # Pitch (F0) - pyin lebih robust untuk suara manusia/bayi dibanding piptrack
    f0, voiced_flag, voiced_prob = librosa.pyin(
        y, fmin=librosa.note_to_hz('C2'), fmax=librosa.note_to_hz('C7'), sr=sr
    )
    f0 = f0[~np.isnan(f0)]
    if len(f0) == 0:
        f0 = np.array([0.0])

    # MFCC (representasi utama)
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)

    return {
        'rms': rms, 'zcr': zcr,
        'spectral_centroid': spectral_centroid, 'spectral_bandwidth': spectral_bandwidth,
        'pitch': f0, 'mfcc': mfcc
    }

"""### 7.2 Feature Engineering (Wajib untuk ML Tradisional)

Setiap fitur time-series (RMS, ZCR, Spectral Centroid, Spectral Bandwidth, Pitch, dan tiap koefisien MFCC) diringkas menjadi 4 statistik: **mean, std, min, max**.

Untuk perbandingan **MFCC vs MFCC+Pitch**, disiapkan dua vektor fitur berbeda.
"""

def summarize_stats(arr, prefix):
    """Ringkas array 1D jadi mean, std, min, max."""
    return {
        f'{prefix}_mean': np.mean(arr), f'{prefix}_std': np.std(arr),
        f'{prefix}_min': np.min(arr), f'{prefix}_max': np.max(arr)
    }

def build_feature_vector(feat_dict, include_pitch=True):
    """Bangun satu baris feature vector (flat) dari feat_dict hasil extract_features_traditional."""
    row = {}
    row.update(summarize_stats(feat_dict['rms'], 'rms'))
    row.update(summarize_stats(feat_dict['zcr'], 'zcr'))
    row.update(summarize_stats(feat_dict['spectral_centroid'], 'centroid'))
    row.update(summarize_stats(feat_dict['spectral_bandwidth'], 'bandwidth'))
    for i in range(feat_dict['mfcc'].shape[0]):
        row.update(summarize_stats(feat_dict['mfcc'][i], f'mfcc{i+1}'))
    if include_pitch:
        row.update(summarize_stats(feat_dict['pitch'], 'pitch'))
    return row

def build_feature_dataframe(segments, labels, include_pitch=True):
    rows = []
    for y in segments:
        feat_dict = extract_features_traditional(y)
        rows.append(build_feature_vector(feat_dict, include_pitch=include_pitch))
    df_feat = pd.DataFrame(rows)
    df_feat['label'] = labels
    return df_feat

# Ekstraksi fitur untuk MFCC + Pitch (fitur lengkap)
print("Ekstraksi fitur train (MFCC + Pitch)...")
train_feat_full = build_feature_dataframe(train_segments_final, train_labels_final, include_pitch=True)
print("Ekstraksi fitur val (MFCC + Pitch)...")
val_feat_full = build_feature_dataframe(val_segments, val_labels, include_pitch=True)
print("Ekstraksi fitur test (MFCC + Pitch)...")
test_feat_full = build_feature_dataframe(test_segments, test_labels, include_pitch=True)

print(f"Shape train (MFCC+Pitch): {train_feat_full.shape}")
train_feat_full.head()

# Siapkan versi MFCC-only (tanpa pitch) untuk perbandingan, dengan drop kolom pitch_*
pitch_cols = [c for c in train_feat_full.columns if c.startswith('pitch_')]

train_feat_mfcc_only = train_feat_full.drop(columns=pitch_cols)
val_feat_mfcc_only = val_feat_full.drop(columns=pitch_cols)
test_feat_mfcc_only = test_feat_full.drop(columns=pitch_cols)

print(f"Shape train (MFCC only): {train_feat_mfcc_only.shape}")
print(f"Shape train (MFCC + Pitch): {train_feat_full.shape}")

"""### 7.3 Mel-Spectrogram (untuk ML Modern: CNN, CNN-LSTM)"""

N_MELS = 128

def extract_melspectrogram(y, sr=SAMPLE_RATE, n_mels=N_MELS):
    mel = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=n_mels)
    mel_db = librosa.power_to_db(mel, ref=np.max)
    return mel_db

def build_melspec_array(segments):
    specs = [extract_melspectrogram(y) for y in segments]
    return np.array(specs)

print("Ekstraksi mel-spectrogram train...")
X_train_mel = build_melspec_array(train_segments_final)
print("Ekstraksi mel-spectrogram val...")
X_val_mel = build_melspec_array(val_segments)
print("Ekstraksi mel-spectrogram test...")
X_test_mel = build_melspec_array(test_segments)

print(f"Shape mel-spectrogram train: {X_train_mel.shape}  (n_samples, n_mels, time_frames)")
print(f"Shape mel-spectrogram val  : {X_val_mel.shape}")
print(f"Shape mel-spectrogram test : {X_test_mel.shape}")

# Visualisasi contoh mel-spectrogram per kelas
fig, axes = plt.subplots(1, len(CLASSES), figsize=(20, 4))
for i, cls in enumerate(CLASSES):
    idx = train_labels_final.index(cls) if cls in train_labels_final else 0
    img = librosa.display.specshow(X_train_mel[idx], sr=SAMPLE_RATE, x_axis='time', y_axis='mel', ax=axes[i], cmap='magma')
    axes[i].set_title(cls)
plt.tight_layout()
plt.show()

"""### 7.4 Ringkasan Total Fitur yang Digunakan"""

# Hitung ulang breakdown fitur tradisional dari kolom aktual dataframe
feat_cols_mfcc_only = [c for c in train_feat_mfcc_only.columns if c != 'label']
feat_cols_full = [c for c in train_feat_full.columns if c != 'label']

n_rms = len([c for c in feat_cols_full if c.startswith('rms_')])
n_zcr = len([c for c in feat_cols_full if c.startswith('zcr_')])
n_centroid = len([c for c in feat_cols_full if c.startswith('centroid_')])
n_bandwidth = len([c for c in feat_cols_full if c.startswith('bandwidth_')])
n_mfcc_feat = len([c for c in feat_cols_full if c.startswith('mfcc')])
n_pitch = len([c for c in feat_cols_full if c.startswith('pitch_')])

print("=== RINGKASAN FITUR — ML TRADISIONAL (SVM, Random Forest) ===")
print(f"Setiap fitur diringkas 4 statistik: mean, std, min, max\n")
print(f"Domain Waktu")
print(f"  - RMS Energy            : {n_rms} fitur")
print(f"  - Zero Crossing Rate    : {n_zcr} fitur")
print(f"Domain Frekuensi")
print(f"  - Spectral Centroid     : {n_centroid} fitur")
print(f"  - Spectral Bandwidth    : {n_bandwidth} fitur")
print(f"Representasi Utama")
print(f"  - MFCC (13 koefisien)   : {n_mfcc_feat} fitur")
print(f"Representasi Tambahan")
print(f"  - Pitch (F0)            : {n_pitch} fitur")
print()
print(f"TOTAL FITUR — MFCC only      : {len(feat_cols_mfcc_only)} fitur")
print(f"TOTAL FITUR — MFCC + Pitch   : {len(feat_cols_full)} fitur")
print()
print("=== RINGKASAN FITUR — ML MODERN (CNN, CNN-LSTM) ===")
print(f"Representasi: Mel-Spectrogram")
print(f"  - Jumlah mel bands (frekuensi) : {X_train_mel.shape[1]}")
print(f"  - Jumlah time frames           : {X_train_mel.shape[2]}")
print(f"  - Total nilai per segmen       : {X_train_mel.shape[1] * X_train_mel.shape[2]} (bentuk 2D, bukan vektor statistik)")

"""---
## 8. Training Model — Machine Learning Tradisional (SVM & Random Forest)

Dilatih dua kali: sekali dengan fitur **MFCC only**, sekali dengan **MFCC + Pitch**, untuk keperluan analisis perbandingan di akhir.
"""

def prepare_xy(df_feat, label_encoder=None, scaler=None, fit=False):
    X = df_feat.drop(columns=['label']).values
    y_raw = df_feat['label'].values
    if fit:
        label_encoder = LabelEncoder()
        y = label_encoder.fit_transform(y_raw)
        scaler = StandardScaler()
        X = scaler.fit_transform(X)
    else:
        y = label_encoder.transform(y_raw)
        X = scaler.transform(X)
    return X, y, label_encoder, scaler

# --- Dataset MFCC + Pitch ---
X_train_full, y_train_full, le_full, scaler_full = prepare_xy(train_feat_full, fit=True)
X_val_full, y_val_full, _, _ = prepare_xy(val_feat_full, le_full, scaler_full)
X_test_full, y_test_full, _, _ = prepare_xy(test_feat_full, le_full, scaler_full)

# --- Dataset MFCC only ---
X_train_mo, y_train_mo, le_mo, scaler_mo = prepare_xy(train_feat_mfcc_only, fit=True)
X_val_mo, y_val_mo, _, _ = prepare_xy(val_feat_mfcc_only, le_mo, scaler_mo)
X_test_mo, y_test_mo, _, _ = prepare_xy(test_feat_mfcc_only, le_mo, scaler_mo)

print("Kelas:", list(le_full.classes_))

# SVM - MFCC + Pitch
svm_full = SVC(kernel='rbf', C=10, gamma='scale', probability=True, random_state=RANDOM_STATE)
svm_full.fit(X_train_full, y_train_full)

# SVM - MFCC only
svm_mo = SVC(kernel='rbf', C=10, gamma='scale', probability=True, random_state=RANDOM_STATE)
svm_mo.fit(X_train_mo, y_train_mo)

print("Training SVM selesai.")

# Random Forest - MFCC + Pitch
rf_full = RandomForestClassifier(n_estimators=300, max_depth=None, random_state=RANDOM_STATE, n_jobs=-1)
rf_full.fit(X_train_full, y_train_full)

# Random Forest - MFCC only
rf_mo = RandomForestClassifier(n_estimators=300, max_depth=None, random_state=RANDOM_STATE, n_jobs=-1)
rf_mo.fit(X_train_mo, y_train_mo)

print("Training Random Forest selesai.")

"""---
## 9. Training Model — Machine Learning Modern (CNN & CNN-LSTM)

Input: mel-spectrogram (`N_MELS x time_frames`), diperlakukan sebagai gambar 2D (ditambah channel dimension).
"""

# Encode label & siapkan input CNN (tambah channel dimension)
le_dl = LabelEncoder()
y_train_dl = le_dl.fit_transform(train_labels_final)
y_val_dl = le_dl.transform(val_labels)
y_test_dl = le_dl.transform(test_labels)

n_classes = len(CLASSES)

# Normalisasi mel-spectrogram (per-dataset min-max sederhana)
def normalize_mel(X):
    return (X - X.min()) / (X.max() - X.min() + 1e-8)

X_train_cnn = normalize_mel(X_train_mel)[..., np.newaxis]  # (N, n_mels, time, 1)
X_val_cnn = normalize_mel(X_val_mel)[..., np.newaxis]
X_test_cnn = normalize_mel(X_test_mel)[..., np.newaxis]

input_shape = X_train_cnn.shape[1:]
print(f"Input shape CNN: {input_shape}")

def build_cnn(input_shape, n_classes):
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Conv2D(32, (3,3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),

        layers.Conv2D(64, (3,3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),

        layers.Conv2D(128, (3,3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),

        layers.GlobalAveragePooling2D(),
        layers.Dense(128, activation='relu'),
        layers.Dropout(0.4),
        layers.Dense(n_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

cnn_model = build_cnn(input_shape, n_classes)
cnn_model.summary()

def build_cnn_lstm(input_shape, n_classes):
    model = models.Sequential([
        layers.Input(shape=input_shape),
        layers.Conv2D(32, (3,3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),

        layers.Conv2D(64, (3,3), activation='relu', padding='same'),
        layers.BatchNormalization(),
        layers.MaxPooling2D((2,2)),

        # Reshape (freq, time, channel) -> (time, freq*channel) untuk LSTM
        layers.Permute((2, 1, 3)),
        layers.Reshape((-1, input_shape[0] // 4 * 64)),

        layers.LSTM(128, return_sequences=False),
        layers.Dropout(0.4),
        layers.Dense(64, activation='relu'),
        layers.Dense(n_classes, activation='softmax')
    ])
    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return model

cnn_lstm_model = build_cnn_lstm(input_shape, n_classes)
cnn_lstm_model.summary()

early_stop = callbacks.EarlyStopping(monitor='val_loss', patience=8, restore_best_weights=True)

history_cnn = cnn_model.fit(
    X_train_cnn, y_train_dl,
    validation_data=(X_val_cnn, y_val_dl),
    epochs=50, batch_size=32, callbacks=[early_stop], verbose=1
)

history_cnn_lstm = cnn_lstm_model.fit(
    X_train_cnn, y_train_dl,
    validation_data=(X_val_cnn, y_val_dl),
    epochs=50, batch_size=32, callbacks=[early_stop], verbose=1
)

# Plot training history
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for hist, name in [(history_cnn, 'CNN'), (history_cnn_lstm, 'CNN-LSTM')]:
    axes[0].plot(hist.history['accuracy'], label=f'{name} - train')
    axes[0].plot(hist.history['val_accuracy'], label=f'{name} - val', linestyle='--')
    axes[1].plot(hist.history['loss'], label=f'{name} - train')
    axes[1].plot(hist.history['val_loss'], label=f'{name} - val', linestyle='--')

axes[0].set_title('Accuracy'); axes[0].set_xlabel('Epoch'); axes[0].legend()
axes[1].set_title('Loss'); axes[1].set_xlabel('Epoch'); axes[1].legend()
plt.tight_layout()
plt.show()

"""---
## 10. Evaluasi Model

Metrik: **Accuracy, Precision, Recall, F1 Score (macro average — cocok untuk data imbalanced), dan Confusion Matrix**, dievaluasi pada **test set** (bukan augmentasi, murni data asli).
"""

def evaluate_model(y_true, y_pred, label_names, model_name):
    acc = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average='macro', zero_division=0)
    rec = recall_score(y_true, y_pred, average='macro', zero_division=0)
    f1 = f1_score(y_true, y_pred, average='macro', zero_division=0)

    print(f"=== {model_name} ===")
    print(f"Accuracy  : {acc:.4f}")
    print(f"Precision : {prec:.4f}")
    print(f"Recall    : {rec:.4f}")
    print(f"F1 Score  : {f1:.4f}")
    print()
    print(classification_report(y_true, y_pred, target_names=label_names, zero_division=0))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(7, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_names, yticklabels=label_names)
    plt.title(f'Confusion Matrix - {model_name}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.tight_layout()
    plt.show()

    return {'model': model_name, 'accuracy': acc, 'precision': prec, 'recall': rec, 'f1_score': f1}

results = []

# SVM
y_pred_svm_full = svm_full.predict(X_test_full)
results.append(evaluate_model(y_test_full, y_pred_svm_full, le_full.classes_, 'SVM (MFCC+Pitch)'))

y_pred_svm_mo = svm_mo.predict(X_test_mo)
results.append(evaluate_model(y_test_mo, y_pred_svm_mo, le_mo.classes_, 'SVM (MFCC only)'))

# Random Forest
y_pred_rf_full = rf_full.predict(X_test_full)
results.append(evaluate_model(y_test_full, y_pred_rf_full, le_full.classes_, 'Random Forest (MFCC+Pitch)'))

y_pred_rf_mo = rf_mo.predict(X_test_mo)
results.append(evaluate_model(y_test_mo, y_pred_rf_mo, le_mo.classes_, 'Random Forest (MFCC only)'))

# CNN
y_pred_cnn_prob = cnn_model.predict(X_test_cnn)
y_pred_cnn = np.argmax(y_pred_cnn_prob, axis=1)
results.append(evaluate_model(y_test_dl, y_pred_cnn, le_dl.classes_, 'CNN (Mel-Spectrogram)'))

# CNN-LSTM
y_pred_cnnlstm_prob = cnn_lstm_model.predict(X_test_cnn)
y_pred_cnnlstm = np.argmax(y_pred_cnnlstm_prob, axis=1)
results.append(evaluate_model(y_test_dl, y_pred_cnnlstm, le_dl.classes_, 'CNN-LSTM (Mel-Spectrogram)'))

"""---
## 11. Perbandingan Model

### 11.1 Perbandingan Fitur: MFCC vs MFCC + Pitch
Dibandingkan langsung pengaruh penambahan fitur pitch terhadap performa SVM dan Random Forest.

### 11.2 Perbandingan ML Tradisional vs ML Modern
Dibandingkan performa terbaik dari tiap kategori (tradisional: SVM/RF berbasis fitur statistik; modern: CNN/CNN-LSTM berbasis mel-spectrogram).
"""

df_results = pd.DataFrame(results)
df_results = df_results.sort_values('f1_score', ascending=False).reset_index(drop=True)
df_results

plt.figure(figsize=(11, 6))
df_plot = df_results.melt(id_vars='model', value_vars=['accuracy', 'precision', 'recall', 'f1_score'],
                           var_name='metric', value_name='score')
sns.barplot(data=df_plot, x='model', y='score', hue='metric')
plt.title('Perbandingan Seluruh Model (Semua Metrik)')
plt.xticks(rotation=30, ha='right')
plt.ylim(0, 1)
plt.legend(title='Metrik', bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.show()

# Fokus: MFCC vs MFCC+Pitch (SVM & RF)
mask_feat_compare = df_results['model'].str.contains('SVM|Random Forest')
df_feat_compare = df_results[mask_feat_compare].copy()

plt.figure(figsize=(9, 5))
sns.barplot(data=df_feat_compare, x='model', y='f1_score', hue='model', palette='coolwarm', legend=False)
plt.title('Perbandingan F1 Score: MFCC only vs MFCC + Pitch')
plt.ylabel('F1 Score (macro)')
plt.xticks(rotation=20, ha='right')
plt.ylim(0, 1)
plt.tight_layout()
plt.show()

print(df_feat_compare[['model', 'accuracy', 'precision', 'recall', 'f1_score']])

# Fokus: Tradisional (terbaik) vs Modern (terbaik)
best_traditional = df_results[df_results['model'].str.contains('SVM|Random Forest')].iloc[0]
best_modern = df_results[df_results['model'].str.contains('CNN')].iloc[0]

df_final_compare = pd.DataFrame([best_traditional, best_modern])
print("Model Tradisional Terbaik vs Model Modern Terbaik:")
df_final_compare[['model', 'accuracy', 'precision', 'recall', 'f1_score']]

"""---
## 12. Perbandingan Sebelum vs Sesudah Augmentasi

Semua model (SVM, RF, CNN, CNN-LSTM) dilatih ulang pakai train set **sebelum augmentasi** (`train_segments`, imbalanced), dibandingkan ke hasil **sesudah augmentasi** yang sudah dilatih di atas. Fitur tradisional pakai varian MFCC+Pitch. Test set tetap sama (tidak diaugmentasi) supaya perbandingan adil.
"""

# Ekstraksi fitur & mel-spectrogram untuk train set SEBELUM augmentasi
print("Ekstraksi fitur (MFCC+Pitch) - train SEBELUM augmentasi...")
train_feat_noaug = build_feature_dataframe(train_segments, train_labels, include_pitch=True)

print("Ekstraksi mel-spectrogram - train SEBELUM augmentasi...")
X_train_mel_noaug = build_melspec_array(train_segments)

print(f"Jumlah data train SEBELUM augmentasi : {len(train_segments)}")
print(f"Jumlah data train SESUDAH augmentasi : {len(train_segments_final)}")

# Siapkan X, y untuk versi sebelum augmentasi (tradisional)
X_train_noaug, y_train_noaug, le_noaug, scaler_noaug = prepare_xy(train_feat_noaug, fit=True)
X_test_noaug, y_test_noaug, _, _ = prepare_xy(test_feat_full, le_noaug, scaler_noaug)

# SVM & RF - versi SEBELUM augmentasi
svm_noaug = SVC(kernel='rbf', C=10, gamma='scale', probability=True, random_state=RANDOM_STATE)
svm_noaug.fit(X_train_noaug, y_train_noaug)

rf_noaug = RandomForestClassifier(n_estimators=300, random_state=RANDOM_STATE, n_jobs=-1)
rf_noaug.fit(X_train_noaug, y_train_noaug)

print("Training SVM & RF (sebelum augmentasi) selesai.")

# CNN & CNN-LSTM - versi SEBELUM augmentasi
y_train_dl_noaug = le_dl.transform(train_labels)
X_train_cnn_noaug = normalize_mel(X_train_mel_noaug)[..., np.newaxis]

cnn_model_noaug = build_cnn(input_shape, n_classes)
history_cnn_noaug = cnn_model_noaug.fit(
    X_train_cnn_noaug, y_train_dl_noaug,
    validation_data=(X_val_cnn, y_val_dl),
    epochs=50, batch_size=32, callbacks=[early_stop], verbose=1
)

cnn_lstm_model_noaug = build_cnn_lstm(input_shape, n_classes)
history_cnn_lstm_noaug = cnn_lstm_model_noaug.fit(
    X_train_cnn_noaug, y_train_dl_noaug,
    validation_data=(X_val_cnn, y_val_dl),
    epochs=50, batch_size=32, callbacks=[early_stop], verbose=1
)

# Evaluasi semua model versi SEBELUM augmentasi
results_noaug = []

y_pred_svm_noaug = svm_noaug.predict(X_test_noaug)
results_noaug.append(evaluate_model(y_test_noaug, y_pred_svm_noaug, le_noaug.classes_, 'SVM (sebelum augmentasi)'))

y_pred_rf_noaug = rf_noaug.predict(X_test_noaug)
results_noaug.append(evaluate_model(y_test_noaug, y_pred_rf_noaug, le_noaug.classes_, 'RF (sebelum augmentasi)'))

y_pred_cnn_noaug = np.argmax(cnn_model_noaug.predict(X_test_cnn), axis=1)
results_noaug.append(evaluate_model(y_test_dl, y_pred_cnn_noaug, le_dl.classes_, 'CNN (sebelum augmentasi)'))

y_pred_cnnlstm_noaug = np.argmax(cnn_lstm_model_noaug.predict(X_test_cnn), axis=1)
results_noaug.append(evaluate_model(y_test_dl, y_pred_cnnlstm_noaug, le_dl.classes_, 'CNN-LSTM (sebelum augmentasi)'))

# Gabungkan hasil sebelum vs sesudah augmentasi jadi satu tabel
results_aug_matched = [r for r in results if r['model'] in
                        ['SVM (MFCC+Pitch)', 'Random Forest (MFCC+Pitch)',
                         'CNN (Mel-Spectrogram)', 'CNN-LSTM (Mel-Spectrogram)']]

model_pair_names = ['SVM', 'RF', 'CNN', 'CNN-LSTM']
rows = []
for name, before, after in zip(model_pair_names, results_noaug, results_aug_matched):
    rows.append({'model': name, 'kondisi': 'Sebelum Augmentasi', 'accuracy': before['accuracy'],
                 'precision': before['precision'], 'recall': before['recall'], 'f1_score': before['f1_score']})
    rows.append({'model': name, 'kondisi': 'Sesudah Augmentasi', 'accuracy': after['accuracy'],
                 'precision': after['precision'], 'recall': after['recall'], 'f1_score': after['f1_score']})

df_aug_compare = pd.DataFrame(rows)
df_aug_compare

fig, axes = plt.subplots(1, 2, figsize=(15, 5))

sns.barplot(data=df_aug_compare, x='model', y='f1_score', hue='kondisi', ax=axes[0], palette='Set2')
axes[0].set_title('F1 Score: Sebelum vs Sesudah Augmentasi')
axes[0].set_ylim(0, 1)

sns.barplot(data=df_aug_compare, x='model', y='accuracy', hue='kondisi', ax=axes[1], palette='Set2')
axes[1].set_title('Accuracy: Sebelum vs Sesudah Augmentasi')
axes[1].set_ylim(0, 1)

plt.tight_layout()
plt.show()

# Selisih (delta) tiap metrik akibat augmentasi
df_pivot = df_aug_compare.pivot(index='model', columns='kondisi', values=['accuracy', 'precision', 'recall', 'f1_score'])
for metric in ['accuracy', 'precision', 'recall', 'f1_score']:
    df_pivot[(metric, 'delta')] = df_pivot[(metric, 'Sesudah Augmentasi')] - df_pivot[(metric, 'Sebelum Augmentasi')]

delta_cols = [(m, 'delta') for m in ['accuracy', 'precision', 'recall', 'f1_score']]
df_pivot[delta_cols]